### ISSUE TITLE
Reporting Bugs and Errors

### ISSUE THREAD

**Issue by sanghyuk-choi** [StableFluffy/LogicKor#19]
좋은 벤치마크를 만들어주셔서 감사드리며, 한국어 LLM 발전에 많은 도움이 되는 것 같습니다.
사용하다 보니 약간의 에러가 있는 것 같아서 리포트 드립니다.

**1.** id:1 의 경우 "위 답변을 영어 문장 3개로 요약한 후. 해당 문장에 있는 단어 3개를 선택하여 단어의 의미를 설명해라." 가 멀티턴 question 인데, 정상적으로 영어로 답변 후 의미를 한국어로 설명하여도 영어로 답변 했다는 이유로 judge_score 가 0.0점입니다. 
https://github.com/StableFluffy/LogicKor/blob/abd987c141a6e639d842a3be8c9884f4533dc8f5/results/judge_HyperClovaX.jsonl#L4

**2.** EVEE-instruct 모델의 [템플릿은](https://huggingface.co/yanolja/EEVE-Korean-Instruct-10.8B-v1.0) 
```
A chat between a curious user and an artificial intelligence assistant. The assistant gives helpful, detailed, and polite answers to the user's questions.
Human: {prompt}
Assistant:
```
와 같은데, 
https://github.com/StableFluffy/LogicKor/blob/abd987c141a6e639d842a3be8c9884f4533dc8f5/templates/template-EEVE.json#L1-L4
와 같이 잘못된 템플릿 파일이 적용되는 것 같습니다.

**3.** 개인 의견 입니다만. 모델 답변 생성시 Sampling Parameter이 beam=4 로 고정되어 있는데, 모델별 Sampling Parameter에 따른 생성결과 차이 편차가 큰 것 같습니다. 
모델의 생성결과가 deterministic 한지를 고려하여 greedy 혹은 beam을 사용하는 것이 맞을 수 있으나, 
API 모델들(gpt, claude, hyperclovaX)은 추정컨데 beam 결과가 아님을 감안하면
다른 sampling 방식을 적용할 수 있도록 수정하면 어떨까 싶습니다. 
많은 open 모델들은 beam 사용시 오히려 점수가 하락하는 것 같습니다.

**Comment by StableFluffy** [comment]
답변이 많이 늦었습니다.

1. 말씀해주신대로, judge에서의 문제가 확실히 존재하는걸로 보입니다. 다만, 각 judge 결과에 대해서 judge 자체의 문제에 따라 결과를 수정하는 것은 형평성 측면에서 문제가 있을 수 있기에, 현재 LogicKor 벤치마크의 한계점으로 바라보면 좋을 것 같습니다. 추후 새로운 벤치마크를 제작한다면 말씀해주신 부분을 고려하겠습니다.

2. 실제 평가 과정에서 어떤 프롬프트를 적용했는지 확실하게 기억나지 않네요. 한번 재평가 후 업로드하도록 하겠습니다.
3. 샘플링 부분은 자유롭게 제출 받도록 하겠습니다.

감사합니다.

**Comment by sanghyuk-choi** [comment]
상세하고 친절한 답변 감사합니다 :)
