### ISSUE TITLE
reference 오류

### ISSUE THREAD

**Issue by simpleusername96** [StableFluffy/LogicKor#2]
안녕하세요, 38번 문제의 reference에 오류가 있는 것 같습니다.

1. {"id": 38, "category": "문법(Grammar)", "questions": ["두 문장 사이에 가장 알맞은 접속어를 고르고, 이유를 설명하시오.\n\n이 세상에는 아름다운 것들이 참으로 많다고들 한다. 나는 그런 아름다움을 모른다.\n\n1. 그래서\n2. 그러나\n3. 그리고\n4. 따라서", "'그러나'와 비슷한 역할을 하는 접속어는 어떤 게 있는지 설명하시오."], "references": ["3. 그리고", null]}
-> 첫 번째 문제의 정답은 "2. 그러나"로 볼 수도 있다고 생각합니다. 두 문장의 내용이 대조적이기 때문입니다. 그러나 현재 references에는 "3. 그리고"라고만 기입되어 있습니다. 이 부분이 평가에 영향을 끼칠 수 있을 것 같습니다.

위 레퍼런스를 수정해주시면 벤치마크의 정확도와 신뢰도를 높일 수 있을 것 같습니다. 
좋은 벤치마크를 만들어주셔서 감사합니다!

**Comment by StableFluffy** [comment]
문제 제기해주셔서 감사합니다.
수정하겠습니다.
