### ISSUE TITLE
Proposal for adding Korean knowledge evaluation data

### ISSUE THREAD

**Issue by js-lee-AI** [StableFluffy/LogicKor#28]
Hello,
My name is Jungseob Lee, a Ph.D. candidate at the NLP&AI Lab at Korea University.

Thank you for your excellent work in advancing the Korean NLP.

I would like to propose adding Korean knowledge evaluation (which most models like LLaMA3 70B struggle with and find difficult to align with English knowledge) and the evaluation of understanding Korean neologisms and idioms (which models like GPT-4 also find confusing) to your LogicKor.

I would like to discuss this matter further. Could I have your email address?
My email is omanma1928@korea.ac.kr.

Thank you for your significant contributions to Korean NLP!

**Comment by StableFluffy** [comment]
Hi I would like to discuss about this topic more.

please contact me through discord

my id is is.maywell
