### ISSUE TITLE
EEVE 템플릿 질문 

### ISSUE THREAD

**Issue by Chad4545** [StableFluffy/LogicKor#48]
- https://github.com/instructkr/LogicKor?tab=readme-ov-file#evaluation-example
EEVE 템플릿 사용한다고 readme.md에 적혀있는데 구체적으로 judge template 을 의미하는 것인가요?https://github.com/instructkr/LogicKor/blob/43c10e5afd8cf5f76c03fc42d8c32a52af506cf8/templates.py#L98

**Comment by StableFluffy** [comment]
과거에 템플릿 사용했때의 흔적인 것 같습니다. 말씀하신대로 현재는 judge_template이 맞습니다. 수정하겠습니다.

**Comment by Chad4545** [comment]
@StableFluffy 혹시 judge template의 reference를  알 수 있을까요?

**Comment by StableFluffy** [comment]
현재는 해당 부분이 맞고 readme에 쓰여있는 부분은 https://github.com/instructkr/LogicKor/blob/old-v1/templates/template-EEVE.json
이거 입니다.
